import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/src/app/components/shared/Navbar";
import { Footer } from "@/src/app/components/shared/Footer";
import { createClient } from "../utils/supabase/server";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const supabase = createClient();

  return (
    <html lang="en">
      <body>

        <Navbar />

        {children}

        <Footer />

      </body>
    </html>
  );
}
